number=2
user_guess=input("For easy, press 1. For medium, press 2. For hard, press 3... if you dare...")
name1=input("What's your name, player1?")
name2=input("What's your name, player2?")
print("Hi,"+ name2)
noun1=input("Give a noun:")
verb1=input("Give a verb:")
direction1=input("Give a direction:")
noun2=input("Give a noun:")
person1=input("Name a person:")
verb2=input("Give a verb:")
place1=input("Name a place:")
verb3=input("Give a verb:")
place2=input("Name a place:")
adj1=input("Give an adjective:")
adj2=input("Give an adjective:")
noun3=input("Give a noun:")
if number<int(user_guess):
	print("Hi,"+ name1)
	print("Hi,"+ name2) 
	print("Do you want to go on the " + noun1 + " with me?")
	print("Sure! You can " + verb1 + " me " + direction1 + " the " + noun2) 
elif number==int(user_guess):
	print("Hi,"+ name1)
	print("Hi,"+ name2)
	print("Do you want to go on the " + noun1 + " with me?")
	print("Sure! You can " + verb1 + " me " + direction1 + " the " + noun2)
	print("My " + person1 + " is picking me up soon. Do you want to " + verb2 + " at the " + place1 + " with us?")
else:
	print("Hi,"+ name1)
	print("Hi,"+ name2)
	print("Do you want to go on the " + noun1 + " with me?")
	print("Sure! You can " + verb1 + " me " + direction1 + " the " + noun2)
	print("My " + person1 + " is picking me up soon. Do you want to " + verb2 + " at the " + place1 + " with us?")
	print("I have to " + verb3 + " first.")
	print("Sweet! I'll wait for you by the " + place2 + " next to the " + adj1 + " man with the " + adj2 + noun3)
	print("Does " + name2 + " make it?")
